services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}

  webapp:
    image: nginx:latest
    container_name: webapp_server
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - '8080:80'
