services:
  daily.cinema.db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    image: daily.cinema.api
    build: .
    ports:
      - ${BACKEND_PORT}:54320
